Repository valueadd-poland/pimp-my-pr, pull requests merged in 2020-01, with the labels that each got.

#43 feat(pmp-api): add pmp-api-e2e application
  angular.json
  apps/pmp-api-e2e/integration/app.spec.ts
  apps/pmp-api-e2e/jest.config.js
  apps/pmp-api-e2e/tsconfig.app.json
  apps/pmp-api-e2e/tsconfig.json
  apps/pmp-api-e2e/tsconfig.spec.json
  apps/pmp-api-e2e/tslint.json
  nx.json
  package-lock.json
  package.json
Labels: enhancement, mvp

#60 feature(pmp-web-user): single user statistics init of libraries
  angular.json
  libs/pmp-web/user/single-user-statistics/feature/README.md
  libs/pmp-web/user/single-user-statistics/feature/jest.config.js
  libs/pmp-web/user/single-user-statistics/feature/src/index.ts
  libs/pmp-web/user/single-user-statistics/feature/src/lib/pmp-web-user-single-user-statistics-feature.ts
  libs/pmp-web/user/single-user-statistics/feature/tsconfig.json
  libs/pmp-web/user/single-user-statistics/feature/tsconfig.lib.json
  libs/pmp-web/user/single-user-statistics/feature/tsconfig.spec.json
  libs/pmp-web/user/single-user-statistics/feature/tslint.json
  nx.json
  tsconfig.json
Labels: enhancement, mvp

#61 feat(pmp-web): users statistics feature
  angular.json
  libs/pmp-web/user/shell/src/lib/containers/user/user.component.scss
  libs/pmp-web/user/shell/src/lib/shell-routing.module.ts
  libs/pmp-web/user/users-statistics/feature/README.md
  libs/pmp-web/user/users-statistics/feature/jest.config.js
  libs/pmp-web/user/users-statistics/feature/src/index.ts
  libs/pmp-web/user/users-statistics/feature/src/lib/containers/users-statistics/users-statistics.component.html
  libs/pmp-web/user/users-statistics/feature/src/lib/containers/users-statistics/users-statistics.component.scss
  libs/pmp-web/user/users-statistics/feature/src/lib/containers/users-statistics/users-statistics.component.ts
  libs/pmp-web/user/users-statistics/feature/src/lib/pmp-web-user-users-statistics-feature.module.spec.ts
  libs/pmp-web/user/users-statistics/feature/src/lib/pmp-web-user-users-statistics-feature.module.ts
  libs/pmp-web/user/users-statistics/feature/src/lib/pmp-web-user-users-statistics-routing.module.ts
  libs/pmp-web/user/users-statistics/feature/src/test-setup.ts
  libs/pmp-web/user/users-statistics/feature/tsconfig.json
  libs/pmp-web/user/users-statistics/feature/tsconfig.lib.json
  libs/pmp-web/user/users-statistics/feature/tsconfig.spec.json
  libs/pmp-web/user/users-statistics/feature/tslint.json
  libs/shared/domain/src/index.ts
  libs/shared/domain/src/lib/models/user-statistics.read-model.ts
  nx.json
  tsconfig.json
  tslint.json
Labels: enhancement, mvp

#57 feat(pmp-api): endpoint for getting users statistics
  apps/pmp-api/tsconfig.app.json
  libs/pmp-api/api-service/repository/api/src/lib/controllers/repository.controller.ts
  libs/pmp-api/api-service/repository/core/src/lib/pmp-api-api-service-repository-core.module.ts
  libs/pmp-api/api-service/repository/core/src/lib/queries/get-user-prs.query.ts
  libs/pmp-api/api-service/repository/core/src/lib/queries/handlers/get-user-prs.handler.ts
  libs/pmp-api/api-service/repository/core/src/lib/queries/handlers/list-repositories.handler.ts
  libs/pmp-api/api-service/repository/core/src/lib/queries/handlers/list-repository-users.handler.ts
  libs/pmp-api/api-service/repository/core/src/lib/queries/list-repository-users.query.ts
  libs/pmp-api/api-service/repository/core/src/lib/repository.facade.ts
  libs/pmp-api/api-service/repository/core/src/lib/services/prs.service.ts
  libs/pmp-api/api-service/repository/core/tsconfig.json
  libs/pmp-api/api-service/repository/data-access/src/lib/domain/entities/github-pr.entity.ts
  libs/pmp-api/api-service/repository/data-access/src/lib/domain/entities/github-user.entity.ts
  libs/pmp-api/api-service/repository/data-access/src/lib/mappers/github-pr.mapper.ts
  libs/pmp-api/api-service/repository/data-access/src/lib/mappers/github-user.mapper.ts
  libs/pmp-api/api-service/repository/data-access/src/lib/repositories/repository.data-service.ts
  libs/pmp-api/api-service/repository/domain/src/index.ts
  libs/pmp-api/api-service/repository/domain/src/lib/models/pr.model.ts
  libs/pmp-api/api-service/repository/domain/src/lib/models/user.model.ts
  libs/pmp-api/api-service/repository/domain/src/lib/read-models/base-repository-statistics.read-model.ts
  libs/pmp-api/api-service/repository/domain/src/lib/read-models/repository-statistics.read-model.ts
  libs/pmp-api/api-service/repository/domain/src/lib/read-models/repository-user-statistics.read-model.ts
  libs/shared/domain/src/index.ts
  libs/shared/domain/src/lib/responses/list-repository-users.response.ts
Labels: enhancement, mvp

#64 feat(pmp-api): add endpoint for getting reviewers statistics
  libs/pmp-api/api-service/repository/api/src/lib/controllers/repository.controller.ts
  libs/pmp-api/api-service/repository/core/src/lib/pmp-api-api-service-repository-core.module.ts
  libs/pmp-api/api-service/repository/core/src/lib/queries/handlers/base-list-repository-users.handler.ts
  libs/pmp-api/api-service/repository/core/src/lib/queries/handlers/list-repository-contributors.handler.ts
  libs/pmp-api/api-service/repository/core/src/lib/queries/handlers/list-repository-reviewers.handler.ts
  libs/pmp-api/api-service/repository/core/src/lib/queries/list-repository-contributors.query.ts
  libs/pmp-api/api-service/repository/core/src/lib/queries/list-repository-reviewers.query.ts
  libs/pmp-api/api-service/repository/core/src/lib/queries/list-repository-users.query.ts
  libs/pmp-api/api-service/repository/core/src/lib/repository.facade.ts
  libs/pmp-api/api-service/repository/data-access/src/lib/repositories/pr.data-service.ts
  libs/pmp-api/api-service/repository/data-access/src/lib/repositories/repository.data-service.ts
  libs/pmp-api/api-service/repository/data-access/tsconfig.json
Labels: enhancement, mvp, pr is waiting

#66 feat(pmp-web-user): create domain lib for user scope
  angular.json
  libs/pmp-web/user/data-access/src/lib/+state/user.actions.ts
  libs/pmp-web/user/data-access/src/lib/+state/user.facade.ts
  libs/pmp-web/user/data-access/src/lib/services/user-data.service.ts
  libs/pmp-web/user/domain/README.md
  libs/pmp-web/user/domain/jest.config.js
  libs/pmp-web/user/domain/src/index.ts
  libs/pmp-web/user/domain/src/lib/payloads/get-user-statistics-collection.payload.ts
  libs/pmp-web/user/domain/src/test-setup.ts
  libs/pmp-web/user/domain/tsconfig.json
  libs/pmp-web/user/domain/tsconfig.lib.json
  libs/pmp-web/user/domain/tsconfig.spec.json
  libs/pmp-web/user/domain/tslint.json
  nx.json
  tsconfig.json
Labels: enhancement, mvp, pr is waiting

#71 feat(pmp-api): get single reviewer statistics
  libs/pmp-api/api-service/repository/api/src/lib/controllers/repository.controller.ts
  libs/pmp-api/api-service/repository/api/src/lib/requests/list-reviewer-statistics.request.ts
  libs/pmp-api/api-service/repository/core/src/lib/pmp-api-api-service-repository-core.module.ts
  libs/pmp-api/api-service/repository/core/src/lib/queries/get-pr-details.query.ts
  libs/pmp-api/api-service/repository/core/src/lib/queries/get-user.query.ts
  libs/pmp-api/api-service/repository/core/src/lib/queries/handlers/get-pr-details.handler.ts
  libs/pmp-api/api-service/repository/core/src/lib/queries/handlers/get-user.handler.ts
  libs/pmp-api/api-service/repository/core/src/lib/queries/handlers/list-reviewer-statistics.handler.ts
  libs/pmp-api/api-service/repository/core/src/lib/queries/list-repositories.query.ts
  libs/pmp-api/api-service/repository/core/src/lib/queries/list-repository-contributors.query.ts
  libs/pmp-api/api-service/repository/core/src/lib/queries/list-repository-reviewers.query.ts
  libs/pmp-api/api-service/repository/core/src/lib/queries/list-reviewer-statistics.query.ts
  libs/pmp-api/api-service/repository/core/src/lib/repository.facade.ts
  libs/pmp-api/api-service/repository/core/src/lib/services/prs.service.ts
  libs/pmp-api/api-service/repository/core/tsconfig.lib.json
  libs/pmp-api/api-service/repository/data-access/src/index.ts
  libs/pmp-api/api-service/repository/data-access/src/lib/domain/entities/github-pr-details.entity.ts
  libs/pmp-api/api-service/repository/data-access/src/lib/domain/entities/github-pr.entity.ts
  libs/pmp-api/api-service/repository/data-access/src/lib/mappers/github-pr-details.mapper.ts
  libs/pmp-api/api-service/repository/data-access/src/lib/mappers/github-pr.mapper.ts
  libs/pmp-api/api-service/repository/data-access/src/lib/pmp-api-api-service-repository-data-access.module.ts
  libs/pmp-api/api-service/repository/data-access/src/lib/repositories/pr.data-service.ts
  libs/pmp-api/api-service/repository/data-access/src/lib/repositories/user.data-service.ts
  libs/pmp-api/api-service/repository/domain/src/index.ts
  libs/pmp-api/api-service/repository/domain/src/lib/interfaces/index.ts
  libs/pmp-api/api-service/repository/domain/src/lib/models/base-repository.model.ts
  libs/pmp-api/api-service/repository/domain/src/lib/models/index.ts
  libs/pmp-api/api-service/repository/domain/src/lib/models/pr-details.model.ts
  libs/pmp-api/api-service/repository/domain/src/lib/models/pr.model.ts
  libs/pmp-api/api-service/repository/domain/src/lib/models/repository.model.ts
  libs/pmp-api/api-service/repository/domain/src/lib/read-models/base-pr-with-changes.read-model.ts
  libs/pmp-api/api-service/repository/domain/src/lib/read-models/index.ts
  libs/pmp-api/api-service/repository/domain/src/lib/read-models/pr-statistics.read-model.ts
  libs/pmp-api/api-service/repository/domain/src/lib/read-models/pr-with-changes.read-model.ts
  libs/pmp-api/api-service/repository/domain/src/lib/read-models/repository-prs-statistics.read-model.ts
  libs/pmp-api/api-service/repository/domain/src/lib/read-models/repository-user-statistics.read-model.ts
  libs/pmp-api/api-service/repository/domain/src/lib/read-models/single-user-statistics.read-model.ts
  libs/shared/domain/src/index.ts
  libs/shared/domain/src/lib/models/pr.statistics.ts
  libs/shared/domain/src/lib/models/repository.model.ts
  libs/shared/domain/src/lib/models/user.model.ts
  libs/shared/domain/src/lib/requests/index.ts
  libs/shared/domain/src/lib/requests/params/index.ts
  libs/shared/domain/src/lib/requests/params/list-reviewer-statistics.params.ts
  libs/shared/domain/src/lib/responses/single-user-statistics.response.ts
Labels: enhancement, mvp

#76 feat(pmp-web): single user statistic data access
  angular.json
  libs/pmp-web/shared/ui-picture-label/src/lib/components/picture-label/picture-label.component.html
  libs/pmp-web/shared/ui-picture-label/src/lib/components/picture-label/picture-label.component.ts
  libs/pmp-web/user/shell/src/lib/shell-routing.module.ts
  libs/pmp-web/user/single-user-statistics/data-access/README.md
  libs/pmp-web/user/single-user-statistics/data-access/jest.config.js
  libs/pmp-web/user/single-user-statistics/data-access/src/index.ts
  libs/pmp-web/user/single-user-statistics/data-access/src/lib/+state/single-user-statistics.actions.ts
  libs/pmp-web/user/single-user-statistics/data-access/src/lib/+state/single-user-statistics.effects.ts
  libs/pmp-web/user/single-user-statistics/data-access/src/lib/+state/single-user-statistics.facade.ts
  libs/pmp-web/user/single-user-statistics/data-access/src/lib/+state/single-user-statistics.reducer.ts
  libs/pmp-web/user/single-user-statistics/data-access/src/lib/+state/single-user-statistics.selectors.ts
  libs/pmp-web/user/single-user-statistics/data-access/src/lib/pmp-web-user-single-user-statistics-data-access.module.spec.ts
  libs/pmp-web/user/single-user-statistics/data-access/src/lib/pmp-web-user-single-user-statistics-data-access.module.ts
  libs/pmp-web/user/single-user-statistics/data-access/src/lib/resources/request-payloads/get-single-user-statistics-response.request-payload.ts
  libs/pmp-web/user/single-user-statistics/data-access/src/lib/services/single-user-statistics-data.service.ts
  libs/pmp-web/user/single-user-statistics/data-access/src/test-setup.ts
  libs/pmp-web/user/single-user-statistics/data-access/tsconfig.json
  libs/pmp-web/user/single-user-statistics/data-access/tsconfig.lib.json
  libs/pmp-web/user/single-user-statistics/data-access/tsconfig.spec.json
  libs/pmp-web/user/single-user-statistics/data-access/tslint.json
  libs/pmp-web/user/single-user-statistics/feature/src/lib/containers/single-user-statistics/single-user-statistics.component.html
  libs/pmp-web/user/single-user-statistics/feature/src/lib/containers/single-user-statistics/single-user-statistics.component.ts
  libs/pmp-web/user/single-user-statistics/feature/src/lib/pmp-web-user-single-user-statistics-feature.module.ts
  nx.json
  tsconfig.json
Labels: enhancement, mvp

#53 feat(pmp-web): basic routing for repository statistics
  .github/workflows/pmp-pr.yml
  angular.json
  libs/pmp-api/api-service/repository/core/src/lib/queries/handlers/list-repository-reviewers.handler.ts
  libs/pmp-web/repository/data-access-repository-statistics/src/lib/services/repository-statistics-data.service.ts
  libs/pmp-web/repository/repositories-statistics/feature/README.md
  libs/pmp-web/repository/repositories-statistics/feature/jest.config.js
  libs/pmp-web/repository/repositories-statistics/feature/src/index.ts
  libs/pmp-web/repository/repositories-statistics/feature/src/lib/containers/repositories-statistics/repositories-statistics.component.html
  libs/pmp-web/repository/repositories-statistics/feature/src/lib/containers/repositories-statistics/repositories-statistics.component.scss
  libs/pmp-web/repository/repositories-statistics/feature/src/lib/containers/repositories-statistics/repositories-statistics.component.ts
  libs/pmp-web/repository/repositories-statistics/feature/src/lib/containers/repositories-statistics/repositories-statistics.presenter.ts
  libs/pmp-web/repository/repositories-statistics/feature/src/lib/pmp-web-repository-repositories-statistics-feature.module.spec.ts
  libs/pmp-web/repository/repositories-statistics/feature/src/lib/pmp-web-repository-repositories-statistics-feature.module.ts
  libs/pmp-web/repository/repositories-statistics/feature/src/lib/pmp-web-repository-repositories-statistics-routing.module.ts
  libs/pmp-web/repository/repositories-statistics/feature/src/test-setup.ts
  libs/pmp-web/repository/repositories-statistics/feature/tsconfig.json
  libs/pmp-web/repository/repositories-statistics/feature/tsconfig.lib.json
  libs/pmp-web/repository/repositories-statistics/feature/tsconfig.spec.json
  libs/pmp-web/repository/repositories-statistics/feature/tslint.json
  libs/pmp-web/repository/shell/src/lib/containers/repositories/repositories.component.html
  libs/pmp-web/repository/shell/src/lib/containers/repositories/repositories.component.scss
  libs/pmp-web/repository/shell/src/lib/containers/repositories/repositories.component.ts
  libs/pmp-web/repository/shell/src/lib/pmp-web-repository-shell.module.ts
  libs/pmp-web/repository/shell/src/lib/shell-routing.module.ts
  libs/pmp-web/shared/ui-sidebar/src/lib/components/sidebar/sidebar.component.html
  libs/pmp-web/shared/ui-sidebar/src/lib/components/sidebar/sidebar.component.scss
  libs/pmp-web/shared/ui-sidebar/src/lib/components/sidebar/sidebar.component.spec.ts
  libs/pmp-web/shared/ui-sidebar/src/lib/pmp-web-shared-ui-sidebar.module.ts
  libs/shared/domain/src/index.ts
  libs/shared/domain/src/lib/responses/list-repositories.response.ts
  libs/shared/domain/src/lib/responses/list-users.response.ts
  nx.json
  package-lock.json
  tsconfig.json
Labels: enhancement, mvp

#85 feature(pmp-web): add app routing module
  apps/pmp-web/src/app/app-routing.module.ts
  apps/pmp-web/src/app/app.module.ts
Labels: enhancement, mvp

#82 refactor(pmp-web): request to api by proxy
  libs/pmp-web/repository/data-access-repository-statistics/src/lib/services/repository-statistics-data.service.ts
  libs/pmp-web/user/data-access/src/lib/services/user-data.service.ts
  libs/pmp-web/user/single-user-statistics/data-access/src/lib/services/single-user-statistics-data.service.ts
Labels: enhancement, mvp

#87 feature(pmp): replace generic table with more specific one
  angular.json
  libs/pmp-api/api-service/repository/api/src/lib/interceptors/response-transform.interceptor.ts
  libs/pmp-api/api-service/repository/core/src/lib/queries/handlers/get-pr-changes.handler.ts
  libs/pmp-api/api-service/repository/core/src/lib/queries/handlers/get-repository-prs.handler.ts
  libs/pmp-api/api-service/repository/core/src/lib/services/prs.service.ts
  libs/pmp-api/api-service/repository/data-access/src/lib/interceptors/github-auth.interceptor.ts
  libs/pmp-api/api-service/repository/domain/src/lib/read-models/repository-statistics.read-model.ts
  libs/pmp-api/api-service/repository/domain/src/lib/read-models/repository-user-statistics.read-model.ts
  libs/pmp-api/shared/config/src/lib/configs/pmp-api-service.config.ts
  libs/pmp-api/shared/config/src/lib/pmp-api-shared-config.module.ts
  libs/pmp-api/shared/domain/src/lib/base/response.ts
  libs/pmp-web/repository/data-access-repository-statistics/tslint.json
  libs/pmp-web/repository/repositories-statistics/feature/src/lib/containers/repositories-statistics/repositories-statistics.component.html
  libs/pmp-web/repository/repositories-statistics/feature/src/lib/containers/repositories-statistics/repositories-statistics.component.scss
  libs/pmp-web/repository/repositories-statistics/feature/src/lib/containers/repositories-statistics/repositories-statistics.component.ts
  libs/pmp-web/repository/repositories-statistics/feature/src/lib/containers/repositories-statistics/repositories-statistics.presenter.ts
  libs/pmp-web/repository/repositories-statistics/feature/src/lib/pmp-web-repository-repositories-statistics-feature.module.ts
  libs/pmp-web/repository/repositories-statistics/feature/tslint.json
  libs/pmp-web/shared/ui-statistics-overview-table/README.md
  libs/pmp-web/shared/ui-statistics-overview-table/jest.config.js
  libs/pmp-web/shared/ui-statistics-overview-table/src/index.ts
  libs/pmp-web/shared/ui-statistics-overview-table/src/lib/pmp-web-shared-ui-statistics-overview-table.module.spec.ts
  libs/pmp-web/shared/ui-statistics-overview-table/src/lib/pmp-web-shared-ui-statistics-overview-table.module.ts
  libs/pmp-web/shared/ui-statistics-overview-table/src/lib/statistics-overview-table/statistics-overview-table.component.html
  libs/pmp-web/shared/ui-statistics-overview-table/src/lib/statistics-overview-table/statistics-overview-table.component.scss
  libs/pmp-web/shared/ui-statistics-overview-table/src/lib/statistics-overview-table/statistics-overview-table.component.ts
  libs/pmp-web/shared/ui-statistics-overview-table/src/test-setup.ts
  libs/pmp-web/shared/ui-statistics-overview-table/tsconfig.json
  libs/pmp-web/shared/ui-statistics-overview-table/tsconfig.lib.json
  libs/pmp-web/shared/ui-statistics-overview-table/tsconfig.spec.json
  libs/pmp-web/shared/ui-statistics-overview-table/tslint.json
  libs/pmp-web/shared/ui-table/README.md
  libs/pmp-web/shared/ui-table/src/index.ts
  libs/pmp-web/shared/ui-table/src/lib/components/table/table.component.html
  libs/pmp-web/shared/ui-table/src/lib/components/table/table.component.ts
  libs/pmp-web/shared/ui-table/src/lib/pmp-web-shared-ui-table.module.spec.ts
  libs/pmp-web/shared/ui-table/src/lib/pmp-web-shared-ui-table.module.ts
  libs/pmp-web/user/data-access/src/lib/+state/user.reducer.ts
  libs/pmp-web/user/data-access/src/lib/+state/user.selectors.ts
  libs/pmp-web/user/data-access/src/lib/pmp-web-user-data-access.module.ts
  libs/pmp-web/user/data-access/tslint.json
  libs/pmp-web/user/domain/tslint.json
  libs/pmp-web/user/single-user-statistics/data-access/tslint.json
  libs/pmp-web/user/users-statistics/feature/src/lib/containers/users-statistics/users-statistics.component.html
  libs/pmp-web/user/users-statistics/feature/src/lib/containers/users-statistics/users-statistics.component.scss
  libs/pmp-web/user/users-statistics/feature/src/lib/containers/users-statistics/users-statistics.component.ts
  libs/pmp-web/user/users-statistics/feature/src/lib/pmp-web-user-users-statistics-feature.module.ts
  libs/pmp-web/user/users-statistics/feature/tslint.json
  libs/shared/domain/src/lib/models/index.ts
  libs/shared/domain/src/lib/models/repository-statistics.interface.ts
  libs/shared/domain/src/lib/models/user.statistics.ts
  libs/shared/domain/src/lib/responses/index.ts
  libs/shared/domain/src/lib/responses/list-repositories.response.ts
  libs/shared/domain/src/lib/responses/list-users.response.ts
  nx.json
  package-lock.json
  tsconfig.json
  tslint.json
Labels: enhancement

#92 fix(pmp-web): remove not necessary tag in dom
  libs/pmp-web/user/single-user-statistics/feature/src/lib/containers/single-user-statistics/single-user-statistics.component.html
Labels: bug, mvp
