Repository valueadd-poland/pimp-my-pr, pull requests merged in 2020-05, with the labels that each got.

#233 docs(): clarifies architecture sources
  CONTRIBUTING.md
Labels: proposal

#235 ci(): run multiple jobs parallel
  .github/workflows/pmp-master.yml
  .github/workflows/pmp-pr.yml
  package.json
Labels: improvement

#241 feat(pmp): allow to add gitlab repo settings.
  libs/server/repository/infrastructure/src/index.ts
  libs/server/repository/infrastructure/src/lib/gitlab/domain/entities/gitlab-repository-namespace.entity.ts
  libs/server/repository/infrastructure/src/lib/gitlab/domain/entities/gitlab-repository-owner.entity.ts
  libs/server/repository/infrastructure/src/lib/gitlab/domain/entities/gitlab-repository.entity.ts
  libs/server/repository/infrastructure/src/lib/gitlab/mappers/map-gitlab-repository.ts
  libs/server/repository/infrastructure/src/lib/gitlab/repositories/gitlab-repository.repository.ts
  libs/server/repository/infrastructure/src/lib/server-repository-infrastructure.module.ts
  libs/server/repository/shell/src/lib/factories/remote-repository-repository.factory.ts
  libs/server/repository/shell/src/lib/server-repository-shell.module.ts
  libs/server/shared/util-repository/src/lib/name-extract/repository-name-extract.util.ts
Labels: enhancement

#231 build(pmp-api): minimize api image
  apps/pmp-api/Dockerfile
  package.json
Labels: improvement

#236 Bugfix/user info
  libs/server/repository/api-rest/src/lib/interceptors/errors.interceptor.ts
  libs/server/user/api-rest/src/lib/controllers/user.controller.ts
  libs/server/user/core/application-services/src/lib/queries/get-user-info/get-user-info.handler.ts
  valueadd-dev.json5
Labels: bug

#234 test(pmp-api-e2e): provide first e2e api tests
  .env-sample
  .github/workflows/pmp-master.yml
  .github/workflows/pmp-pr.yml
  angular.json
  apps/pmp-api-e2e/fixtures/responses/api.github.com-repos-valueadd-poland-pimp-my-pr.ts
  apps/pmp-api-e2e/fixtures/responses/api.github.com-user.ts
  apps/pmp-api-e2e/fixtures/responses/github.com-login-oauth-access_token.ts
  apps/pmp-api-e2e/integration/app.spec.ts
  apps/pmp-api-e2e/integration/auth.spec.ts
  apps/pmp-api-e2e/integration/repository.spec.ts
  apps/pmp-api-e2e/jest.config.js
  apps/pmp-api-e2e/tsconfig.json
  apps/pmp-api-e2e/utils/clear-db.util.ts
  apps/pmp-api-e2e/utils/mock-http.service.ts
  apps/pmp-api/src/app/app.module.ts
  apps/pmp-api/src/main.ts
  libs/server/auth/infrastructure/src/lib/server-auth-infrastructure.module.ts
  libs/server/repository/api-rest/src/lib/dtos/add-repository.dto.ts
  libs/server/repository/api-rest/src/lib/server-repository-api-rest.module.ts
  libs/server/shared/config/src/lib/pmp-api-config.service.ts
  libs/server/shared/core-api-rest/README.md
  libs/server/shared/core-api-rest/jest.config.js
  libs/server/shared/core-api-rest/src/index.ts
  libs/server/shared/core-api-rest/src/lib/exception-filters/http.exception-filter.ts
  libs/server/shared/core-api-rest/src/lib/interceptors/errors.interceptor.ts
  libs/server/shared/core-api-rest/src/lib/interceptors/response-transform.interceptor.ts
  libs/server/shared/core-api-rest/src/lib/server-shared-core-api-rest.module.ts
  libs/server/shared/core-api-rest/tsconfig.json
  libs/server/shared/core-api-rest/tsconfig.lib.json
  libs/server/shared/core-api-rest/tsconfig.spec.json
  libs/server/shared/core-api-rest/tslint.json
  libs/server/shared/core/src/lib/modules/type-orm-root.module.ts
  libs/server/user/infrastructure/src/lib/server-user-infrastructure.module.ts
  nx.json
  package-lock.json
  tsconfig.json
  tslint.json
  valueadd-dev.json5
Labels: improvement

#256 feat(security): encrypt remote token in jwt
  .env-sample
  .github/workflows/pmp-master.yml
  .github/workflows/pmp-pr.yml
  angular.json
  libs/server/auth/core/application-services/src/lib/queries/get-access-token.query.ts/get-access-token.handler.ts
  libs/server/auth/infrastructure-remote-token-crypto/README.md
  libs/server/auth/infrastructure-remote-token-crypto/jest.config.js
  libs/server/auth/infrastructure-remote-token-crypto/src/index.ts
  libs/server/auth/infrastructure-remote-token-crypto/src/lib/server-auth-infrastructure-remote-token-crypto.module.ts
  libs/server/auth/infrastructure-remote-token-crypto/src/lib/server-auth-infrastructure-remote-token-crypto.service.ts
  libs/server/auth/infrastructure-remote-token-crypto/tsconfig.json
  libs/server/auth/infrastructure-remote-token-crypto/tsconfig.lib.json
  libs/server/auth/infrastructure-remote-token-crypto/tsconfig.spec.json
  libs/server/auth/infrastructure-remote-token-crypto/tslint.json
  libs/server/auth/infrastructure/src/lib/guards/auth.guard.ts
  libs/server/auth/port/README.md
  libs/server/auth/port/jest.config.js
  libs/server/auth/port/src/index.ts
  libs/server/auth/port/src/lib/remote-token-crypto.service.ts
  libs/server/auth/port/tsconfig.json
  libs/server/auth/port/tsconfig.lib.json
  libs/server/auth/port/tsconfig.spec.json
  libs/server/auth/port/tslint.json
  libs/server/auth/shell/src/lib/server-auth-shell.module.ts
  libs/server/shared/config/src/lib/pmp-api-config.service.ts
  nx.json
  tsconfig.json
  tslint.json
  valueadd-dev.json5
Labels: improvement
